import express from 'express';
import itemsHandler from '../api/items.js';
import syncHandler from '../api/sync.js';
import syncRunHandler from '../api/sync/run.js';
import emailHandler from '../api/email.js';
import healthHandler from '../api/health.js';
import systemHealthHandler from '../api/health/system.js';
import logsHandler from '../api/logs.js';
import sourcesHandler from '../api/sources.js';
import relationsHandler from '../api/relations.js';
import testHandler from '../api/test.js';
import indexHandler from '../api/index.js';
import loginHandler from '../api/auth/login.js';
import signupHandler from '../api/auth/signup.js';
import meHandler from '../api/auth/me.js';
import logoutHandler from '../api/auth/logout.js';
import backupHandler from '../api/admin/backup.js';
import statsHandler from '../api/admin/stats.js';
import uploadHandler from '../api/upload.js';
import deleteFileHandler from '../api/files/delete.js';

const app = express();
app.use(express.json({ limit: '1mb' }));

app.get('/api', (req, res) => indexHandler(req, res));
app.get('/api/test', (req, res) => testHandler(req, res));
app.get('/api/items', (req, res) => itemsHandler(req, res));
app.post('/api/items', (req, res) => itemsHandler(req, res));
app.delete('/api/items', (req, res) => itemsHandler(req, res));
app.post('/api/sync', (req, res) => syncHandler(req, res));
app.post('/api/sync/run', (req, res) => syncRunHandler(req, res));
app.post('/api/email', (req, res) => emailHandler(req, res));
app.get('/api/health', (req, res) => healthHandler(req, res));
app.get('/api/health/system', (req, res) => systemHealthHandler(req, res));
app.get('/api/logs', (req, res) => logsHandler(req, res));
app.get('/api/sources', (req, res) => sourcesHandler(req, res));
app.post('/api/sources', (req, res) => sourcesHandler(req, res));
app.get('/api/relations', (req, res) => relationsHandler(req, res));
app.post('/api/relations', (req, res) => relationsHandler(req, res));
app.post('/api/auth/signup', (req, res) => signupHandler(req, res));
app.post('/api/auth/login', (req, res) => loginHandler(req, res));
app.get('/api/auth/me', (req, res) => meHandler(req, res));
app.post('/api/auth/logout', (req, res) => logoutHandler(req, res));
app.post('/api/admin/backup', (req, res) => backupHandler(req, res));
app.get('/api/admin/stats', (req, res) => statsHandler(req, res));
app.post('/api/upload', (req, res) => uploadHandler(req, res));
app.post('/api/files/delete', (req, res) => deleteFileHandler(req, res));

export default app;
